version: '3'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - mongo
      - redis
  
  mongo:
    image: mongo:latest
    volumes:
      - mongo_volume:/data/db

  redis:
    image: redis:alpine
    volumes:
      - redis_volume:/data

volumes:
  mongo_volume:
  redis_volume:
