version: "3"

services:

  backend:
    build:
      context: ./backend
    ports:
      - "8000:80"
    volumes:
      - ./storage:/storage
    depends_on:
      - postgres
      - mongodb

  postgres:
    image: postgres:16-alpine
    container_name: postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    healthcheck:
       test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
       interval: 5s
       timeout: 5s
       retries: 5
    volumes:
      - ./data:/var/lib/postgresql/data2

  mongodb:
    image: mongo:latest
    container_name: mongodb
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - ./mongodbdata:/data/db
      - ./init-mongo:/docker-entrypoint-initdb.d
    command: >
      bash -c "mongod --bind_ip_all & sleep 5 && mongo --eval 'db = db.getSiblingDB(\"mongodb\"); db.createUser({user: \"mongouser\", pwd: \"mongopassword\", roles: [{ role: \"readWrite\", db: \"mongodb\" }]});' && mongod --bind_ip_all"
