version: "3"

services:
  frontend:
    build: ./frontend
    ports:
      - "80:4173"

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - mongo
      - redis
    volumes:
      - files_volume:/files
    environment:
      - DEBUG=${DEBUG}

  mongo:
    image: mongo:latest
    volumes:
      - mongo_volume:/data/db

  redis:
    image: redis:alpine
    volumes:
      - redis_volume:/data

  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    container_name: mailserver
    hostname: xn--90abdibneekjf0abcbbqil3bejr0c1r.xn--p1ai
    env_file: mailserver.env
    ports:
      - "25:25"
      - "143:143"
      - "465:465"
      - "587:587"
      - "993:993"
    volumes:
      - ./docker-data/dms/mail-data/:/var/mail/
      - ./docker-data/dms/mail-state/:/var/mail-state/
      - ./docker-data/dms/mail-logs/:/var/log/mail/
      - ./docker-data/dms/config/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
    restart: always
    stop_grace_period: 1m
    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 0

volumes:
  mongo_volume:
  redis_volume:
  files_volume:
