version: "3"

services:
  frontend:
    build: ./next
    ports:
      - "80:3000"

  backend:
    build:
      context: ./backend
      target: prod
    ports:
      - "8000:8000"
    volumes:
      - ./storage:/storage
