version: "3"

services:
  backend:
    build:
      target: dev
    environment:
      - DEBUG=true
    develop:
      watch:
        - action: sync
          path: ./backend/app/
          target: /app/app
        - action: rebuild
          path: ./backend/poetry.lock
