version: "3"

services:
  frontend:
    build: ./next
    ports:
      - "80:3000"

  backend:
    build:
      context: ./backend
      target: prod
    ports:
      - "8000:8000"
    volumes:
      - ./storage:/storage
    depends_on:
      - dynamodb

  dynamodb:
    command: "-jar DynamoDBLocal.jar -disableTelemetry -inMemory -sharedDb"
    image: "amazon/dynamodb-local:latest"
    ports:
      - "8080:8000"
