#!/bin/sh
case $1 in
  prod)
    docker-compose up --build
    ;;

  dev)
    docker-compose -f docker-compose.yml -f docker-compose.dev.yml watch --no-up &
    docker-compose -f docker-compose.yml -f docker-compose.dev.yml up --build
    ;;

  test:watch)
    docker-compose -f docker-compose.yml -f docker-compose.test.yml watch --no-up &
    docker-compose -f docker-compose.yml -f docker-compose.test.yml up --build
    ;;

  *)
    echo "Usage: $0 <dev|test:watch|prod>"
    exit 1
    ;;
esac
