/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ChangeUserSchema {
    'newPhone'?: string | null;
    'newFio'?: string | null;
    'newEmail'?: string | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "newPhone",
            "baseName": "new_phone",
            "type": "string",
            "format": ""
        },
        {
            "name": "newFio",
            "baseName": "new_fio",
            "type": "string",
            "format": ""
        },
        {
            "name": "newEmail",
            "baseName": "new_email",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ChangeUserSchema.attributeTypeMap;
    }

    public constructor() {
    }
}
