"""Create tables

Revision ID: 2fe310433d8f
Revises: 
Create Date: 2024-12-15 02:00:12.660708

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2fe310433d8f"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("verification")
    op.drop_table("company_info")
    op.drop_table("ip_info")
    op.alter_column(
        "docs",
        "id",
        existing_type=sa.BIGINT(),
        type_=sa.String(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "docs",
        "id",
        existing_type=sa.String(),
        type_=sa.BIGINT(),
        existing_nullable=False,
    )
    op.create_table(
        "ip_info",
        sa.Column("inn", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("fio", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("ogrn", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("address", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("inn", name="ip_info_pkey"),
    )
    op.create_table(
        "company_info",
        sa.Column("inn", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("ogrn", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("address", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("inn", name="company_info_pkey"),
    )
    op.create_table(
        "verification",
        sa.Column("request_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("sms_code", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("phone", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("request_id", name="verification_pkey"),
    )
    # ### end Alembic commands ###
