/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class EnterpriseInfo {
    'id': number | null;
    'name': string | null;
    'type': string | null;
    'createId': number | null;
    'inn': string | null;
    'ogrn': string | null;
    'address': string | null;
    'imageId': string | null;
    'generalTypeActivity': string | null;
    'createdAt': Date | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string",
            "format": ""
        },
        {
            "name": "createId",
            "baseName": "create_id",
            "type": "number",
            "format": ""
        },
        {
            "name": "inn",
            "baseName": "inn",
            "type": "string",
            "format": ""
        },
        {
            "name": "ogrn",
            "baseName": "ogrn",
            "type": "string",
            "format": ""
        },
        {
            "name": "address",
            "baseName": "address",
            "type": "string",
            "format": ""
        },
        {
            "name": "imageId",
            "baseName": "image_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "generalTypeActivity",
            "baseName": "general_type_activity",
            "type": "string",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "Date",
            "format": "date-time"
        }    ];

    static getAttributeTypeMap() {
        return EnterpriseInfo.attributeTypeMap;
    }

    public constructor() {
    }
}
