/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ImageModel {
    'id': string;
    /**
    * Name of the uploaded file
    */
    'filename': string;
    /**
    * MIME type of the file
    */
    'contentType': string;
    /**
    * ISO 8601 formatted upload date
    */
    'uploadDate': string;
    /**
    * Base64 encoded image data
    */
    'imageData': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "filename",
            "baseName": "filename",
            "type": "string",
            "format": ""
        },
        {
            "name": "contentType",
            "baseName": "content_type",
            "type": "string",
            "format": ""
        },
        {
            "name": "uploadDate",
            "baseName": "upload_date",
            "type": "string",
            "format": ""
        },
        {
            "name": "imageData",
            "baseName": "image_data",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ImageModel.attributeTypeMap;
    }

    public constructor() {
    }
}
