/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class PointInfo {
    'id': number;
    'enterpriseId': number;
    'title': string;
    'address': string;
    'openingTime': string;
    'closingTime': string;
    'imageId': string | null;
    'documentsData': Array<string> | null;
    'socialData': Array<any> | null;
    'phone': string | null;
    'typeActivity': string;
    'middleStars': number | null;
    'verifyPhone': boolean | null;
    'createdAt': Date;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": ""
        },
        {
            "name": "enterpriseId",
            "baseName": "enterprise_id",
            "type": "number",
            "format": ""
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string",
            "format": ""
        },
        {
            "name": "address",
            "baseName": "address",
            "type": "string",
            "format": ""
        },
        {
            "name": "openingTime",
            "baseName": "opening_time",
            "type": "string",
            "format": "time"
        },
        {
            "name": "closingTime",
            "baseName": "closing_time",
            "type": "string",
            "format": "time"
        },
        {
            "name": "imageId",
            "baseName": "image_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "documentsData",
            "baseName": "documents_data",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "socialData",
            "baseName": "social_data",
            "type": "Array<any>",
            "format": ""
        },
        {
            "name": "phone",
            "baseName": "phone",
            "type": "string",
            "format": ""
        },
        {
            "name": "typeActivity",
            "baseName": "type_activity",
            "type": "string",
            "format": ""
        },
        {
            "name": "middleStars",
            "baseName": "middle_stars",
            "type": "number",
            "format": ""
        },
        {
            "name": "verifyPhone",
            "baseName": "verify_phone",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "Date",
            "format": "date-time"
        }    ];

    static getAttributeTypeMap() {
        return PointInfo.attributeTypeMap;
    }

    public constructor() {
    }
}
