/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class UserSchema {
    'id': number;
    'phone': string;
    'fio': string;
    'email': string | null;
    'verifyPhone': boolean;
    'verifyEmail': boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": ""
        },
        {
            "name": "phone",
            "baseName": "phone",
            "type": "string",
            "format": ""
        },
        {
            "name": "fio",
            "baseName": "fio",
            "type": "string",
            "format": ""
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string",
            "format": ""
        },
        {
            "name": "verifyPhone",
            "baseName": "verify_phone",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "verifyEmail",
            "baseName": "verify_email",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return UserSchema.attributeTypeMap;
    }

    public constructor() {
    }
}
