import { StyleSheet } from 'react-native';


export default StyleSheet.create({
    //все до следующего комма в основоном действует глобально на страницу
    background: {
        flex: 1,
      },
      container: {
        flex: 1,
        justifyContent: "space-between",
        alignItems: "center",
        paddingHorizontal: 20,
        paddingVertical: 20,
      },
      containerMainPage: {
        flex: 1,
        paddingHorizontal: 20,
        paddingVertical: 20,
      },
      containerProfile: {
        weight: "100%",
        paddingHorizontal: 25,
        marginTop: 20,
      },
      containerButtonsDocuments: {
        width: "100%",
        marginTop: 91,
        paddingHorizontal: 25,
      },
      containerButtonsSocial: {
        width: "100%",
        marginTop: 163,
        paddingHorizontal: 25,
      },
      containerButtonsMenuPages: {
        width: "100%",
        height: 120,
        paddingHorizontal: 25,
        paddingVertical: 10,
        marginBottom: 33,
        flex: 1,
        justifyContent: 'flex-end',
      },
      textDescriptionProfile: {
        marginBottom: 12,
        fontSize: 18,
        fontWeight: "500",
        color: "#FFFFFF",
      }, 
      textInputProfile: {
        width: "100%",
        height: 60,
        alignItems: "flex-start",
        backgroundColor: "#FFFFFF",
        borderTopRightRadius: 10,
        borderBottomLeftRadius: 10,
        borderBottomRightRadius: 10,
        fontSize: 18,
      },
      switchContainer: {
        width: "100%",
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: "space-between",
        marginTop: 36,
        paddingHorizontal: 25,
      },
      switchText: {
        fontSize: 18,
        fontWeight: "500",
        color: "#FFFFFF",
        marginRight: 10,
      },
      buttonMenuPage: {
        width: "100%",
        height: 45,
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: "#FAFBFF",
        borderTopRightRadius: 10,
        borderTopLeftRadius: 10,
        borderBottomLeftRadius: 10,
      },
      buttonBackMenuPage: {
        width: "100%",
        height: 45,
        alignItems: "center",
        justifyContent: "center",
        borderWidth: 1,
        borderColor: '#FAFBFF',
        borderTopRightRadius: 10,
        borderTopLeftRadius: 10,
        borderBottomRightRadius: 10,
      },
      textInButtonsMenuPage: {
        fontSize: 18,
        color: "#313231",
        fontWeight: "700"
      },
      textInButtonsBackMenuPage: {
        fontSize: 18,
        color: "#FAFBFF",
        fontWeight: "600"
      },
      buttonDocuments: {
        width: "100%",
        height: 45,
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: "#FFFFFF",
        borderTopRightRadius: 10,
        borderBottomLeftRadius: 10,
        borderBottomRightRadius: 10,
      },
      textInButtonsMenuPage: {
        fontSize: 15,
        color: "#313231",
        fontWeight: "500",
      },
      footerButtonTextDocuments: {
        fontSize: 15,
        fontWeight: "Bold",
        color: "#FFFFFF",
        marginTop: 13,
      },
      header: {
        alignItems: "center",
        marginTop: 20,
      },
      menuHeader: {
        width: '100%',
        alignItems: 'flex-start',
        marginTop: 181,
        marginStart:20,
        paddingLeft: 10,
      },
      profileHeader: {
        width: "100%",
        alignItems: 'center',
      },
      menuPagesFooterHeader: {
        width: "100%",
        alignItems: 'flex-start',
      },
      menuPagesHeader: {
        width: "100%",
        alignItems: 'flex-start',
        marginTop: 10,
        marginStart: 25,
      },
      menuPagesSecondHeader: {
        width: "100%",
        alignItems: 'flex-start',
        marginTop: 28,
        marginStart: 25,
      },
      headerLeft: {
        alignItems: "flex-start",
        marginTop: 20,
      },
      title: {
        fontSize: 24,
        fontFamily: 'Montserrat',
        fontWeight: "bold",
        color: "#FFFFFF",
        textAlign: "center",
        marginBottom: 10,
      },
      menuTitle: {
        fontFamily: 'Montserrat',
        fontSize: 30,
        fontWeight: "bold",
        color: "#FFFFFF",
      },
      subtitle: {
        fontFamily: 'Montserrat',
        fontSize: 14,
        color: "#FFFFFF",
        textAlign: "center",
      },
      titleSimple: {
        fontSize: 18,
        fontFamily: 'Montserrat',
        color: "#FFFFFF",
        marginBottom: 10,
        alignSelf: "flex-start",
      },
      profileTitle: {
        fontSize: 24,
        color: "#FFFFFF",
        fontWeight: "400",
        marginTop: 142,
      },
      //Это можно использовать для View, который располагает кнопки
      buttons: {
        width: "100%",
        alignItems: "center",
        marginTop: 40,
      },
      menuTopButtons: {
        width: "100%",
        flexDirection: 'row',
        justifyContent: 'center',
        gap: 15,
        paddingStart: 25,
        paddingEnd: 24,
        marginTop: 43,
      },
      menuBottomButtons: {
        flexDirection: "row",
        flexWrap: "wrap",
        justifyContent: 'space-between',
        width: "100%",
        gap: 10,
        paddingStart: 20,
        paddingEnd: 40, 
        marginTop: 73,
        marginBottom: 245,
      },
      //Это белая кнопка с черным текстом
      WhiteButton: {
        width: "100%",
        backgroundColor: "#FFFFFF",
        paddingVertical: 15,
        alignItems: "center",
        marginBottom: 15,
        borderTopLeftRadius: 10,
        borderTopRightRadius: 10,
        borderBottomLeftRadius: 10,
      },
      whiteButtonMenuTopActive: {
        flex: 1,
        height: 77,
        backgroundColor: "#FFFFFF",
        paddingTop: 25,
        paddingStart: 15,
        paddingBottom: 20,
        paddingEnd:15,
        borderTopLeftRadius: 20,
        borderTopRightRadius: 20,
        borderBottomLeftRadius: 20,
      },
      whiteButtonMenuTopNoActive: {
        flex: 1,
        height: 77,
        backgroundColor: "#C3C2C2",
        paddingTop: 25,
        paddingStart: 15,
        paddingBottom: 20,
        paddingEnd:15,
        borderTopLeftRadius: 20,
        borderTopRightRadius: 20,
        borderBottomLeftRadius: 20,
      },
      whiteButtonMenuBottomActive: {
        width: '48%',
        height: 128,
        backgroundColor: "#FFFFFF",
        paddingTop: 23,
        paddingStart: 16,
        paddingBottom: 10,
        paddingEnd: 30,
        borderTopLeftRadius: 20,
        borderTopRightRadius: 20,
        borderBottomLeftRadius: 20,
        
      },
      blackText: {
        fontFamily: 'Montserrat',
        fontSize: 15,
        fontWeight: "bold",
        color: "#000000",
      },
      alertText: {
        fontFamily: 'Montserrat',
        fontSize: 11,
        color: "#D83731",
      },
      //Это кнопка сливающаяся с фоном и текс белый
      DefButton: {
        width: "100%",
        borderWidth: 2,
        borderColor: "#FFFFFF",
        paddingVertical: 15,
        alignItems: "center",
        borderTopLeftRadius: 10,
        borderTopRightRadius: 10,
        borderBottomRightRadius: 10,
      },
      DefText: {
        fontFamily: 'Montserrat',
        fontSize: 16,
        fontWeight: "bold",
        color: "#FFFFFF",
      },
      //текст уточнение
      footerText: {
        fontSize: 12,
        color: "#FFFFFF",
        textAlign: "center",
        fontFamily: 'Montserrat',
        marginBottom: 20,
      },
      footerDocumentsText: {
        fontSize: 18,
        color: "#FFFFFF",
        marginStart: 25,
        marginTop: 50,
        textAlign: "center",
      },
      TextField: {
        width: 350,
        height: 50,
        borderRadius: 5,
        backgroundColor: "white",
        paddingLeft: 10,
        marginBottom: 15,
      },
      scrollContainer: {
        flexGrow: 1,
        justifyContent: "center",
        alignItems: "center",
      },
      fields: {
        width: "100%",
        alignItems: "center",
        marginTop: 40
      },
      //Эти три стиля предназначены для того, чтбы делать наложения
      passwordContainer: {
        position: "relative",
        width: 350,
        marginBottom: 15,
      },
      iconButton: {
        position: "absolute",
        right: 10,
        top: 12,
      },
      icon: {
        width: 24,
        height: 24,
        tintColor: "#007BFF",
      },
      containerLine: {
        paddingStart: 24,
        paddingEnd: 91,
        width: '100%',
        marginTop: 10,
      },
      menuPagesLine: {
        width: '100%',
        height: 1, 
        backgroundColor: '#FFFFFF',
      },
  });